package initRouter

import (
	"github.com/swaggo/files"       // swagger embed files
	"github.com/swaggo/gin-swagger" // gin-swagger middleware

	// swagger 文档生成在本项目中的目录，必须导入这个目录文档才能正常显示
	_ "GinHello/docs" // docs is generated by Swag CLI, you have to import it.
)

// SwaggerRouter swagger 路由
// 文档访问地址：http://localhost:8080/swagger/index.html
// @title Gin swagger
// @version 1.0
// @description Gin swagger 示例项目
// @contact.name yangyi
// @contact.email 1024569696@qq.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
func SwaggerRouter() {
	// The url pointing to API definition
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json")
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
}
