definitions:
  model.Article:
    properties:
      content:
        type: string
      id:
        type: integer
      type:
        type: string
    type: object
  model.Result:
    properties:
      code:
        example: 0
        type: integer
      data:
        type: object
      message:
        example: 请求信息
        type: string
    type: object
  model.Role:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  model.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      password:
        type: string
      role:
        items:
          $ref: '#/definitions/model.Role'
        type: array
      updatedAt:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /article:
    get:
      consumes:
      - application/json
      description: 查询所有文章
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
      summary: 查询所有文章
      tags:
      - 文章管理
    post:
      consumes:
      - application/json
      description: 提交新的文章内容
      parameters:
      - description: 文章
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.Article'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.Result'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Result'
      summary: 添加文章
      tags:
      - 文章管理
    put:
      consumes:
      - application/json
      description: 更新文章内容
      parameters:
      - description: 文章
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.Article'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.Result'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Result'
      summary: 更新文章
      tags:
      - 文章管理
  /article/{id}:
    delete:
      consumes:
      - application/json
      description: 通过 id 删除指定文章
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Result'
      summary: 删除文章
      tags:
      - 文章管理
    get:
      consumes:
      - application/json
      description: 通过 id 查询指定文章
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Result'
      summary: 查询文章
      tags:
      - 文章管理
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录签发 JWT
      parameters:
      - description: 用户
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "99":
          description: ""
          schema:
            $ref: '#/definitions/model.Result'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
      summary: 用户登录
      tags:
      - 用户管理
  /user/register:
    post:
      consumes:
      - application/json
      description: 注册用户并保存到数据库
      parameters:
      - description: 用户
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "99":
          description: ""
          schema:
            $ref: '#/definitions/model.Result'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
      summary: 用户注册
      tags:
      - 用户管理
swagger: "2.0"
